### ISSUE TITLE
Ergonomics of GIT_INSTAFIX_UPSTREAM

### ISSUE THREAD

**Issue by mightyiam** [quodlibetor/git-instafix#23]
I do find myself using GIT_INSTAFIX_UPSTREAM often enough that I began to wish for better ergonomics.

**Comment by mightyiam** [comment]
Perhaps the UX could be interactive in this use case, as well? Travel up the tree interactively?

**Comment by quodlibetor** [comment]
ah 100%, I've been meaning to search for `main`, `master`, `develop`, `trunk` [here](https://github.com/quodlibetor/git-instafix/blob/ae80ee8ec3f135644ed4ee769ff35afe461e8725/src/lib.rs#L210-L212) for awhile.

If you feel like adding it that would be fine, otherwise I'll add it eventually.

**Comment by mightyiam** [comment]
Thank you!
