### ISSUE TITLE
Do I need to be on a different branch?

### ISSUE THREAD

**Issue by opdavies** [quodlibetor/git-instafix#35]
I'm working locally on my `main` branch, tracking `origin/main`. I do trunk-based development, so rarely create topic branches.

My local branch is three commits ahead of the remote branch, but I get this error when running `git instafix`:

> Error: selecting commit to amend: No commits between main (cfc2a5d253) and cfc2a5d253599bf6b36e636bc6fa918ca67cd4ab

Does git-instafix assume I'm working on a different branch and merging into something like `main` or `master`?

I expected it to allow me to select from my local commits that weren't yet pushed to my remote, and run a fixup on those.

**Comment by quodlibetor** [comment]
ah, I always work on branches so I made that the most convenient.

You can get the list of changes between you and `origin/main` temporarily with `-u origin/main` or more permanently with `git config instafix.default-upstream-branch origin/main`

**Comment by opdavies** [comment]
> You can get the list of changes between you and `origin/main` temporarily with `-u origin/main` or more permanently with `git config instafix.default-upstream-branch origin/main`

Thanks. I'll give it a try.

**Comment by quodlibetor** [comment]
You probably ran into `Error: creating merge base: cannot locate local branch 'origin/main'; class=Reference (4); code=NotFound (-3)`

I just released 0.2.6 which should fix that problem and give a better error message for main-only workflows.

**Comment by opdavies** [comment]
Thanks, @quodlibetor! I've just updated to 0.2.7, so I'll try it out and report any further issues.
