### ISSUE TITLE
Allow rev for GIT_INSTAFIX_UPSTREAM

### ISSUE THREAD

**Issue by mightyiam** [quodlibetor/git-instafix#37]
I just tried providing a tag. Seems like a branch is expected. Would it make sense to allow it to be a rev?

**Comment by quodlibetor** [comment]
yeah there's no reason not to.

If you didn't mind sharing why you wanted to update something since a tag out might help me think of other things that should also work.

**Comment by mightyiam** [comment]
Thank you. I was in a branch in which history might diverge from the tracked branch. It was the only branch in the clone and the tracked was the only branch in the remote.

**Comment by quodlibetor** [comment]
Ah that makes sense, thanks. I *have* had repos that behaved like that, just not in awhile.

Feel free to re-open this issue if the released fix doesn't... fix it.
